### ISSUE TITLE
cTAKES custom dictionary setup documentation

### ISSUE THREAD

**Issue by andytubeee** [apache/ctakes#19]
I have a CSV file of dictionary vocabulary and concept code. Are there any documentations on how we can set up a custom dictionary for when using **bin/runClinicalPipeline.sh**?

Thanks

**Comment by seanfinan** [comment]
There is/was documentation somewhere, but it is spread out and would take me some time to find the latest and most accurate.  However, you have have a look at the example here https://github.com/apache/ctakes/blob/main/ctakes-dictionary-lookup-fast/src/user/resources/org/apache/ctakes/dictionary/lookup/fast/bsv/tinyDict.bsv
Column 1 has the cui, 2 has the tui, 3 the synonym.  If there is a 4th entry then it is used as the preferred text for the concept.  The lookupXml for the example is here: https://github.com/apache/ctakes/blob/main/ctakes-dictionary-lookup-fast/src/user/resources/org/apache/ctakes/dictionary/lookup/fast/bsv/tinyDictSpec.xml
You just want to point to that lookupXml file.  on the command line "-l bsv/tinyDictSpec.xml".  You may need to use the full path.  This all uses the code here: https://github.com/apache/ctakes/blob/main/ctakes-dictionary-lookup-fast/src/main/java/org/apache/ctakes/dictionary/lookup2/dictionary/BsvRareWordDictionary.java
and here: https://github.com/apache/ctakes/blob/main/ctakes-dictionary-lookup-fast/src/main/java/org/apache/ctakes/dictionary/lookup2/concept/BsvConceptFactory.java
If you aren't certain about the tui you can use T000 for Unknown

**Comment by seanfinan** [comment]
https://github.com/apache/ctakes/wiki/ctakes-dictionary-lookup-fast
If you expand DictionarySubPipe https://github.com/apache/ctakes/wiki/ctakes-dictionary-lookup-fast#dictionary-sub-pipe you can see where the cli parameter for "LookupXml" is set to lower-case L
If you get this working and feel comfortable writing a couple of lines on a custom BSV dictionary for the wiki, please put it in a comment here.  Thanks

**Comment by andytubeee** [comment]
Thanks for sharing, I converted csv to bsv, then created a xml based on your tinyDictSpec.xml, and then used the -l flag with ./bin/runClinicalPipeline.

I didn't run into any issue with the pipeline, thus I am assuming it worked.

I think you can put the example links in the current wiki because it was really straightforward to build yourself.

**Comment by seanfinan** [comment]
Hi Andrew,

Thank you for the update!

Sean
________________________________
